<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(RootDir)\Module.targets" />

  <ItemGroup>
    <CSharpProject Include="Refly\Refly.csproj" />
    <CSharpProject Include="Refly.Cons\Refly.Cons.csproj" />
    <CSharpProject Include="XsdTidy\XsdTidy.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="Refly\bin\Refly.dll" />
    <Binary Include="Refly\bin\Refly.pdb" />

    <Binary Include="XsdTidy\bin\XsdTidy.exe" />
  </ItemGroup>

  <ItemGroup>
    <DocumentedAssembly Include="Refly\bin\Refly.dll" />
  </ItemGroup>
</Project>
