<Project xmlns="http://schemas.microsoft.com/developer/msbuild/2003">
  <Import Project="$(RootDir)\Module.targets" />

  <ItemGroup>
    <CSharpProject Include="QuickGraph\QuickGraph.csproj" />
    <CSharpProject Include="QuickGraph.Algorithms\QuickGraph.Algorithms.csproj" />
    <CSharpProject Include="QuickGraph.Algorithms.GraphViz\QuickGraph.Algorithms.GraphViz.csproj" />
    <CSharpProject Include="QuickGraph.Tests\QuickGraph.Tests.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Binary Include="QuickGraph\bin\QuickGraph.dll" />
    <Binary Include="QuickGraph\bin\QuickGraph.pdb" />
    <Binary Include="QuickGraph.Algorithms\bin\QuickGraph.Algorithms.dll" />
    <Binary Include="QuickGraph.Algorithms\bin\QuickGraph.Algorithms.pdb" />
    
    <Binary Include="QuickGraph.Algorithms.Graphviz\bin\QuickGraph.Algorithms.Graphviz.dll" />

    <Binary Include="NGraphviz\NGraphviz.dll" />
    <Binary Include="NGraphviz\NGraphviz.Layout.dll" />
    <Binary Include="NGraphviz\NGraphviz.Helpers.dll" />
  </ItemGroup>

  <ItemGroup>
    <DocumentedAssembly Include="QuickGraph\bin\QuickGraph.dll" />
    <DocumentedAssembly Include="QuickGraph.Algorithms\bin\QuickGraph.Algorithms.dll" />
    <DocumentedAssemly Include="QuickGraph.Algorithms.Graphviz\bin\QuickGraph.Algorithms.Graphviz.dll" />
  </ItemGroup>

  <ItemGroup>
    <TestAssembly Include="QuickGraph.Tests\bin\QuickGraph.Tests.dll" />
  </ItemGroup>
</Project>
