//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
using System.Xml.Serialization;

namespace NCover
{

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(TypeName="coverage-type", Namespace="http://tempuri.org/Coverage.xsd")]
	[System.Xml.Serialization.XmlRootAttribute("coverage", Namespace="http://tempuri.org/Coverage.xsd", IsNullable=false)]
	public class coveragetype 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("module")]
		public moduletype[] Items;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(TypeName="module-type", Namespace="http://tempuri.org/Coverage.xsd")]
	public class moduletype 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("method")]
		public methodtype[] method;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string assembly;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(TypeName="method-type", Namespace="http://tempuri.org/Coverage.xsd")]
	public class methodtype 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("seqpnt")]
		public seqpnttype[] seqpnt;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string name;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string @class;
	}

	/// <remarks/>
	[System.Xml.Serialization.XmlTypeAttribute(TypeName="seqpnt-type", Namespace="http://tempuri.org/Coverage.xsd")]
	public class seqpnttype 
	{
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int visitcount;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int line;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int column;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int endline;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public int endcolumn;
    
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string document;
	}
}