//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

namespace MbUnit.Framework.Testers 
{
	using System;
	
	
	/// <include file="MbUnit.Framework.Doc.xml" path="doc/summaries/summary[@name='MbUnit.Framework.Testers']"/>
	internal class NamespaceDoc
	{
	}
}
