using System;
using System.Text;
using System.Collections;
using System.Reflection;
using MbUnit.Core.Invokers;
using MbUnit.Core.Framework;
using MbUnit.Core.Runs;

namespace MbUnit.Framework
{
    /// <summary>
    /// A single test case of a <see cref="TestSuite"/>.
    /// </summary>
    public class TestCase : ITestCase
    {
        private string name;
        private Delegate testDelegate;
        private Object[] parameters;
        private IRunInvoker invoker;
        private string description=null;

        /// <summary>
        /// Initializes a new <see cref="TestCase"/> instance
        /// with <paramref name="name"/>, <paramref name="testDelegate">delegate</paramref> and
        /// <paramref name="parameters"/> if applicable.
        /// </summary>
        /// <param name="name">Name of the test case</param>
        /// <param name="testDelegate">Delegate called by the test case</param>
        /// <param name="parameters">Parameters of the delegate</param>
        /// <exception cref="ArgumentNullException">
        /// Thrown if <paramref name="name"/> or <paramref name="testDelegate"/> is null
        /// </exception>
        /// <exception cref="ArgumentException">
        /// Thrown if <paramref name="name"/> is the empty string.
        /// </exception>
        public TestCase(string name, Delegate testDelegate, params Object[] parameters)
        {
            if (name == null)
                throw new ArgumentNullException("name");
            if (name.Length == 0)
                throw new ArgumentException("name is empty");
            if (testDelegate == null)
                throw new ArgumentNullException("testDelegate");
            this.name = name;
            this.testDelegate = testDelegate;
            this.parameters = parameters;

            DelegateRunInvoker delegateInvoker = new DelegateRunInvoker(new TestCaseRun(), testDelegate, parameters);
            this.invoker = DecoratorPatternAttribute.DecoreInvoker(testDelegate.Method, delegateInvoker);
        }

        /// <summary>
        /// Gets or sets the description of the test case.
        /// </summary>
        /// <value>The description of the test case.</value>
        public string Description
        {
            get
            {
                return this.description;
            }
            set
            {
                this.description = value;
            }
        }

        /// <summary>
        /// Gets the test delegate.
        /// </summary>
        /// <value>The test delegate.</value>
        public Delegate TestDelegate
        {
            get { return this.testDelegate; }
        }

        /// <summary>
        /// Gets the parameters (signature) for the test.
        /// </summary>
        /// <returns>An <see cref="Object"/> array</returns>
        public Object[] GetParameters()
        {
            return this.parameters;
        }

        /// <summary>
        /// Gets the name of the test case
        /// </summary>
        /// <value>
        /// The name of the test case
        /// </value>
        public virtual String Name
        {
            get
            {
                return this.name;
            }
        }

        /// <summary>
        /// Invokes test using the parameters returned by <see cref="GetParameters"/>.
        /// </summary>
        /// <returns>Return value of the invoked test method. If the method returns void, null
        /// is returned.</returns>
        public virtual object Invoke(Object o, IList args)
        {
            return this.invoker.Execute(o, this.parameters);
        }

        private sealed class TestCaseRun : Run
        {
            /// <summary>
            /// Initializes a new instance of the <see cref="TestCaseRun"/> class.
            /// </summary>
            public TestCaseRun()
                :base("TestCase",true)
            { }
            /// <summary>
            /// Populates the <see cref="RunInvokerTree"/> invoker graph
            /// with <see cref="IRunInvoker"/> generated by the run. <b>Not supported</b> in this class
            /// </summary>
            /// <param name="tree">Invoker tree</param>
            /// <param name="parent">parent vertex</param>
            /// <param name="t">class type that is marked by the run</param>
            /// <remarks>
            /// Not Supported by the <see cref="TestCaseRun"/> class.
            /// </remarks>
            public override void Reflect(RunInvokerTree tree, RunInvokerVertex parent, Type t)
            {
                throw new NotSupportedException();
            }
        }
    }
}
