//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=1.1.4322.573.
// 
namespace GUnit.Core.Reports.Xsd {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="report-result", Namespace="http://tempuri.org/gunit-report.xsd")]
    [System.Xml.Serialization.XmlRootAttribute("report-result", Namespace="http://tempuri.org/gunit-report.xsd", IsNullable=false)]
    public class reportresult {
        
        /// <remarks/>
        public reportcounter counter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("assembly", IsNullable=false)]
        public reportassembly[] assemblies;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.DateTime date;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="report-counter", Namespace="http://tempuri.org/gunit-report.xsd")]
    public class reportcounter {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("run-count")]
        public int runcount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("success-count")]
        public int successcount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("failure-count")]
        public int failurecount;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute("ignore-count")]
        public int ignorecount;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="report-exception", Namespace="http://tempuri.org/gunit-report.xsd")]
    public class reportexception {
        
        /// <remarks/>
        public string message;
        
        /// <remarks/>
        public string source;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("stack-trace")]
        public string stacktrace;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inner-exception", IsNullable=true)]
        public reportexception innerexception;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="report-invoker", Namespace="http://tempuri.org/gunit-report.xsd")]
    public class reportinvoker {
        
        /// <remarks/>
        public string description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="report-run", Namespace="http://tempuri.org/gunit-report.xsd")]
    public class reportrun {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("invoker", IsNullable=false)]
        public reportinvoker[] invokers;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("console-out", IsNullable=true)]
        public string consoleout;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("console-error", IsNullable=true)]
        public string consoleerror;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public reportexception exception;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public reportrunresult result;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public System.Double duration;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public long memory;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="report-run-result", Namespace="http://tempuri.org/gunit-report.xsd")]
    public enum reportrunresult {
        
        /// <remarks/>
        success,
        
        /// <remarks/>
        failure,
        
        /// <remarks/>
        ignore,
        
        /// <remarks/>
        notrun,
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="report-fixture", Namespace="http://tempuri.org/gunit-report.xsd")]
    public class reportfixture {
        
        /// <remarks/>
        public reportcounter counter;
        
        /// <remarks/>
        public string description;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("run", IsNullable=false)]
        public reportrun[] runs;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string type;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="report-namespace", Namespace="http://tempuri.org/gunit-report.xsd")]
    public class reportnamespace {
        
        /// <remarks/>
        public reportcounter counter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("namespace", IsNullable=false)]
        public reportnamespace[] namespaces;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("fixture", IsNullable=false)]
        public reportfixture[] fixtures;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="report-assembly", Namespace="http://tempuri.org/gunit-report.xsd")]
    public class reportassembly {
        
        /// <remarks/>
        public reportcounter counter;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("namespace", IsNullable=false)]
        public reportnamespace[] namespaces;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string name;
    }
}
